[package]
name = "web3-infura"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
num-format = "0.4.4"
tokio = "1.25.0"
web3 = "0.18.0"
